-- Run this SQL in Supabase SQL Editor for the backend_supabase service

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  email text unique,
  password_hash text not null,
  points integer not null default 5,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.images (
  id bigint generated by default as identity primary key,
  public_id text not null unique,
  format text not null,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  likes_count integer not null default 0,
  comments_count integer not null default 0
);

create table if not exists public.unlocked_images (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  image_id bigint not null references public.images(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  unique (user_id, image_id)
);

create table if not exists public.image_likes (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  image_id bigint not null references public.images(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, image_id)
);

create table if not exists public.image_comments (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  image_id bigint not null references public.images(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_images_created_at on public.images(created_at);
create index if not exists idx_images_updated_at on public.images(updated_at);
create index if not exists idx_images_likes_count on public.images(likes_count);
create index if not exists idx_images_comments_count on public.images(comments_count);
create index if not exists idx_unlocked_user_image on public.unlocked_images(user_id, image_id);
create index if not exists idx_image_comments_image_id on public.image_comments(image_id);
create index if not exists idx_image_likes_image_id on public.image_likes(image_id);
